CREATE TABLE IF NOT EXISTS public.mini_sites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  site_name TEXT NOT NULL,
  slug TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  template_key TEXT NOT NULL DEFAULT 'premium-v1',
  primary_color TEXT NOT NULL DEFAULT '#f97316',
  slogan TEXT,
  logo_url TEXT,
  hero_image_url TEXT,
  hero_title TEXT,
  hero_subtitle TEXT,
  about_text TEXT,
  highlights JSONB NOT NULL DEFAULT '[]'::jsonb,
  gallery_images JSONB NOT NULL DEFAULT '[]'::jsonb,
  contact_email TEXT,
  contact_phone TEXT,
  cta_label TEXT,
  cta_url TEXT,
  seo_title TEXT,
  seo_description TEXT,
  custom_domain TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT mini_sites_user_id_unique UNIQUE (user_id),
  CONSTRAINT mini_sites_slug_unique UNIQUE (slug),
  CONSTRAINT mini_sites_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);